#
# Makefile for MyCalculator project
#
# created sept. 23, 2013
#

all: default

default:
	xcodebuild build

clean:
	rm -rvf Build* build* DerivedData* \
		MyCalculator.xcodeproj/xcuserdata* \
		MyCalculator.xcodeproj/project.xcworkspace*
	rm -v `find . -name .DS_Store`
